# on: [push]
name: build-docker-image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # -
      #   name: Build and push base
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./
      #     file: ./DockerfileBase
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring_base:latest
      -
        name: Build and push build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./DockerfileBuild
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring_build:latest
      # -
      #   name: Build and push template
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring_template:latest
